services:
  erddap:
    container_name: erddap
    image: erddap/erddap:20251121T183110
    restart: unless-stopped
    hostname: dummy-erddap
    ports:
      - 8080:8080

    volumes:
      - ./conf:/usr/local/tomcat/content/erddap
      - ./erddapData:/erddapData   # bind mount for ERDDAP internal data
      - ./datasets:/datasets # bind mount for user data files
      - ./conf/digi4eco.png:/usr/local/tomcat/webapps/erddap/images/logo.png:ro
